version: '1'

services:
BDB:

container_name: Bigchaindb
build: 
contect: .

dockerfile: bigchain.dockerfile

ports:
- "9984:9984"


networks:
- bigchain-network



MG:

container_name: Mongo
build: 
context: .

dockerfile: mongodb.dockerfile

ports:
- "27017:27017"

networks:
- bigchain-network



networks:

- bigchain-network:
     driver: bridge
