version: '2'

services:
  bigchaindb:
    container_name: Bigchaindb
    build: ./bigchain
    ports:
      - "9984:9984"
    networks:
      - bigchain

  mongo:
    container_name: Mongo
    build: ./mongo
    ports:
    - "27017:27017"
    networks:
      - bigchain

networks:
  bigchain:


